@startuml

actor HR as "Data analyst"

rectangle Database

rectangle "Cities" {
    usecase UC4 as "Get cities
    by country in world"

    usecase UCa as "Print cities"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml