@startuml

actor HR as "Data analyst"

rectangle Database

rectangle "Countries" {
    usecase UC4 as "Get countries
    by name in world"

    usecase UCa as "Print countries"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml