@startuml

actor HR as "Data analyst"

rectangle Database

rectangle "Languages" {
    usecase UC4 as "Get languages
    by popularity in country"

    usecase UCa as "Print languages"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml